Repository sb-ai-lab/HypEx, pull requests merged in 2024-03, with the labels that each got.

#35 [FEATURE] Implement Emissions Handling in HypEx
  hypex/algorithms/faiss_matcher.py
  hypex/matcher.py
  hypex/utils/validators.py
Labels: enhancement

#37 [FIX] Cholesky Decomposition Adjustment
  hypex/algorithms/faiss_matcher.py
Labels: bug, enhancement

#29 [BUG] Data creation with given number of users
  hypex/utils/tutorial_data_creation.py
Labels: bug

#39 [FEATURE] Bias Contribution Assessment to ATT
  hypex/algorithms/faiss_matcher.py
Labels: enhancement

#41 [FEATURE] Implement Imbalanced Sample Size Calculation
  hypex/ab_test/aa_tester.py
Labels: enhancement

#10 Advanced Multiple Testing Solution via limit distribution.
  examples/tutorials/Tutorial_4_Test_Limit_Distribution.ipynb
  examples/tutorials/Tutorial_5_Modeling_Limit_Distribution.ipynb
  hypex/ab_test/limit_distribution.py
Labels: enhancement

#43 [FEATURE] Add Warnings for Alpha Version Functionalities
  README.md
  docs/pages/modules/matcher.rst
  docs/pages/modules/selectors.rst
  docs/pages/modules/utils.rst
  examples/tutorials/Tutorial_1_Matching.ipynb
  hypex/matcher.py
  hypex/selectors/feature_selector.py
  hypex/utils/validators.py
Labels: documentation, enhancement

#45 [DOCUMENTATION] Update tutorials
  examples/tutorials/Tutorial_1_Matching.ipynb
  examples/tutorials/Tutorial_2_AAtesting.ipynb
  examples/tutorials/Tutorial_3_ABtesting.ipynb
  hypex/ab_test/aa_tester.py
  hypex/ab_test/ab_tester.py
  hypex/ab_test/limit_distribution.py
  hypex/algorithms/faiss_matcher.py
Labels: documentation, enhancement

#48 Feature/experiments
  docs/pages/Tutorials.rst
  docs/pages/experiments/Predict_Model_Effect.nblink
  docs/pages/tutorials/Tutorial_4_Test_Limit_Distribution.nblink
  docs/pages/tutorials/Tutorial_5_Modeling_Limit_Distribution.nblink
  examples/experiments/Predict_Model_Effect.ipynb
  examples/tutorials/Tutorial_2_AAtesting.ipynb
Labels: enhancement

#53 Enhancements to `group_col` Handling in HypEx
  hypex/algorithms/faiss_matcher.py
  hypex/matcher.py
Labels: bug

#54 Added support 3.11 and 3.12. Moved from alpha to beta. Updated versions
  pyproject.toml
Labels: enhancement

#55 Optimization and Bug Fix for limit_distribution_function in HypEx
  hypex/ab_test/limit_distribution.py
Labels: bug

#50 Reformatted Dataset structure
  hypex/dataset/backends/pandas_backend.py
  hypex/dataset/dataset.py
  hypex/dataset/roles.py
  hypex/hypotheses/base.py
  hypex/hypotheses/hypothesis.py
  hypex/hypotheses/hypothesis_scheme.json
  hypex/hypotheses/output.json
  hypex/hypotheses/test_config.json
  tutorial_dataset.ipynb
Labels: enhancement

#58 [DOCS] Documentation Update - Addition of Code of Conduct
  CODE_OF_CONDUCT.md
  pyproject.toml
Labels: documentation

#59 [FEATURE] Adding a parameter to fill in the gaps in group_col
  hypex/matcher.py
Labels: enhancement

#60 [FEATURE] Added the restrictions on categorical column
  hypex/matcher.py
Labels: enhancement

#56 [FEATURE] Edit readme. Added examples
  README.md
Labels: documentation, enhancement
