Repository sb-ai-lab/HypEx, pull requests merged in 2024-02, with the labels that each got.

#19 Feature/mde usability
  examples/tutorials/Tutorial_2_AAtesting.ipynb
  hypex/ab_test/aa_tester.py
  tests/test_aa.py
Labels: enhancement

#23 BUG with tqdm
  hypex/ab_test/aa_tester.py
  hypex/algorithms/faiss_matcher.py
  hypex/matcher.py
Labels: bug

#17 Started developing new dataset (In progress)
  hypex/dataset/backends/pandas_backend.py
  hypex/dataset/base.py
  hypex/dataset/dataset.py
  hypex/dataset/roles.py
  hypex/dataset/utils.py
  hypex/utils/hypex_typings.py
Labels: enhancement

#26 New features
  hypex/dataset/backends/pandas_backend.py
  hypex/dataset/base.py
  hypex/dataset/dataset.py
  tutorial_dataset.ipynb
Labels: bug, enhancement

#24 Matching with group_col validation
  hypex/algorithms/faiss_matcher.py
  hypex/matcher.py
Labels: bug, enhancement

#28 FEATURES loc, iloc, add_column
  hypex/dataset/backends/pandas_backend.py
  hypex/dataset/base.py
  hypex/dataset/dataset.py
  tutorial_dataset.ipynb
Labels: enhancement

#30 [FEATURE] add_column, set_value
  hypex/dataset/backends/pandas_backend.py
  hypex/dataset/base.py
  hypex/dataset/dataset.py
  hypex/dataset/roles.py
  tutorial_dataset.ipynb
Labels: enhancement

#33 [FEATURE] dataset creation from dictionary for new architecture
  hypex/dataset/backends/pandas_backend.py
  hypex/dataset/base.py
  hypex/dataset/dataset.py
  tutorial_dataset.ipynb
Labels: enhancement
