Repository sb-ai-lab/HypEx, pull requests merged in 2025-02, with the labels that each got.

#133 Replace pre-commit with Tox and Fix Documentation Generation
  .pre-commit-config.yaml
  docs/index.rst
  pyproject.toml
  tox.ini
Labels: documentation

#134 [HEI-455] Dataset tests
  coverage.sh
  hypex/dataset/abstract.py
  hypex/dataset/backends/pandas_backend.py
  hypex/dataset/dataset.py
  hypex/dataset/roles.py
  hypex/hypotheses/__init__.py
  unitests/unitests.py
Labels: enhancement

#130 Fix default mode for AA test
  examples/tutorials/AA Test.ipynb
  hypex/ab_test/aa_tester.py
Labels: bug

#148 updated last version with old architecture with warnings
  hypex/__init__.py
  pyproject.toml
Labels: enhancement

#147 Dev/architecture v11 aa mode
  hypex/aa.py
Labels: enhancement
